# Generated by Django 3.0.6 on 2020-06-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
