# Generated by Django 3.0.6 on 2020-06-09 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_image_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='last_name',
            new_name='name2',
        ),
    ]
